server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: ${SSL_ENABLE}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  messages:
    basename: messages
    encoding: UTF-8
  elasticsearch:
    uris: http://localhost:9200
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  kafka:
    bootstrap-servers: localhost:9093
    admin:
      client-id: admin-client
    streams:
      application-id: schema-change-processor
      properties:
        processing.guarantee: at_least_once
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
    consumer:
      group-id: test
      auto-offset-reset: earliest
      enable-auto-commit: false  # 수동 커밋 설정
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  ${DB_USER_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    #    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://ohgiraffers:ohgiraffers@localhost:10001/forecasthub?authSource=admin
    redis:
      host: localhost
      port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mail:
    host: email.master-of-prediction.shop
    username: admin@master-of-prediction.shop
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: email.master-of-prediction.shop
  profiles:
    active: ${PROFILES_ACTIVE}

jwt:
  expiration_time: 86400000 #1일
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: '*' # 모든 엔드포인트를 노출
  endpoint:
    prometheus:
      enabled: true # Prometheus 엔드포인트 활성화
minio:
  url: http://125.132.216.190:9000
  accessKey: MY-USER
  secretKey: MY-PASSWORD
  bucketName: user-files
logging:
  level:
    com:
      com.outsider: DEBUG
    org:
      elasticsearch:
        client: DEBUG
      springframework:
        data:
          elasticsearch: DEBUG
