server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: false
spring:
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    gateway:
      mvc:
        routes:
          - id: after_route
            uri: https://httpbin.org/get
            predicates:
              - Path=/test
            filters:
              - RewritePath=/test, /get
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  ${DB_USER_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    #    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://ohgiraffers:ohgiraffers@localhost:10001/forecasthub?authSource=admin
    redis:
      host: localhost
      port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mail:
    host: email.master-of-prediction.shop
    username: admin@master-of-prediction.shop
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: email.master-of-prediction.shop
  profiles:
    active: ${PROFILES_ACTIVE}

jwt:
  expiration_time: 86400000 #1일
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: '*' # 모든 엔드포인트를 노출
  endpoint:
    prometheus:
      enabled: true # Prometheus 엔드포인트 활성화
minio:
  url: http://localhost:9000
  accessKey: MY-USER
  secretKey: MY-PASSWORD
  bucketName: sns-files