input {
    tcp {
        port => 5044
        codec => json_lines
    }
}

filter {
    # JSON 로그에서 필요한 필드 추출
    json {
        source => "message"
    }

    mutate {
        # 필요한 필드만 남기기
        remove_field => ["@version", "host", "port", "path"]
    }
}

output {
    stdout { codec => rubydebug } # 콘솔 출력 (디버깅용)
    elasticsearch {
        hosts => ["http://localhost:9200"]
        index => "feed-interactions-%{+YYYY.MM.dd}"
    }
}
